### ISSUE TITLE
I found the "Memory Error" when running your code.

### ISSUE THREAD

**Issue by HiHippie** [sirius-mhlee/selective-search-for-object-recognition#1]
I found the "Memory Error" when running your code. Could you tell me how to fix it? Many thanks!

**Comment by sirius-mhlee** [comment]
> I found the "Memory Error" when running your code. Could you tell me how to fix it? Many thanks!

Hi. now, i'm running my code. but i couldn't found any error.
Could you tell me more information about your "Memory Error"? Thanks!
And, i am using "Anaconda 4.6.14"
